- hosts: all
  become: true
  tasks:
    - name: Request certs
      command: |
        certbot certonly --standalone --cert-name {{ item.name }} -d {{ item.domains | join(',') }} \
          --non-interactive --agree-tos --email {{ email }} \
          --http-01-port=8888 --preferred-challenges=http-01
      loop: "{{ certs }}"
    
    - name: Make certs ready for HAProxy
      shell: |
        cat \
          /etc/letsencrypt/live/{{ item.name }}/fullchain.pem \
          /etc/letsencrypt/live/{{ item.name }}/privkey.pem > \
          /etc/ssl/haproxy/{{ item.name }}.pem
      loop: "{{ certs }}"
  vars:
    # ===== <IMPORTANT> =====
    email: PLEASE_ENTER_VALID_EMAIL@gmail.com
    # ===== </IMPORTANT> =====
    certs:
      - name: academlyceum
        domains:
          - smartmail.academlyceum.zp.ua
          - netschool.academlyceum.zp.ua
          - students.academlyceum.zp.ua
      - name: oskr
        domains:
          - oskr.org
          - about.oskr.org
          - monitor.oskr.org
